name: Build and Test

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            version: [ netcoreapp3.1,net5.0,net6.0 ]
          - os: windows-latest
              version: [ net462,netcoreapp3.1,net5.0,net6.0 ]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run Tests with Coverage
        run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
        
        #      - name: Codecov
        #        uses: codecov/codecov-action@master
        