name: 'Deploy to NuGet'

on:
  push:
    branches: [ main ]

env:
  PACKAGE_OUTPUT_DIRECtORY: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'
  
jobs:
  deploy:
    name: 'Deploy'
    runs-on: 'windows-latest'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Install dotnet'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'

      - name: 'Restore Packages'
        run: dotnet restore

      - name: 'Build Project'
        run: dotnet build Cisco.Otel.Distribution.Tracing/Cisco.Otel.Distribution.Tracing.csproj --no-restore --configuration Release

      - name: 'Pack Project'
        run: dotnet pack Cisco.Otel.Distribution.Tracing/Cisco.Otel.Distribution.Tracing.csproj --no-restore --no-build --configuration Release --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

#      - name: 'Push Package'
#        run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\*.nupkg -s ${{ env.NUGET_SOURCE_URL }}